portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from resume.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", home, name="home"),
    path("contact/", contact, name="contact_link"),
    path("about/", about, name="about_me"),
    path("hobbies/", hobbies, name="my_hobbies"),
    path("projects/", ProjectListView.as_view(), name="projects"),
    path("project/<pk>/", ProjectDetailView.as_view(), name="project"),
]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/models.py
from django.db import models

# Create your models here.
from cloudinary.models import CloudinaryField


class ResumeProject(models.Model):

    start_date = models.DateField(("Start Date"), auto_now=False, auto_now_add=False)
    ongoing = models.BooleanField(("Ongoing"))
    name = models.CharField(("Title"), max_length=50, null=False, blank=False)
    quick_blurb = models.CharField(
        ("Quick Blurb"), max_length=200, null=False, blank=False
    )
    long_description = models.TextField(("Long Description"), blank=True)
    git_link = models.CharField(("Git Link"), max_length=200, blank=True)
    # main_img = models.ImageField(("Image Upload"), upload_to="resume/")
    main_img = CloudinaryField("Image Upload")
    difficulty = models.IntegerField(("Difficulty"), default=0)
    tools_used = models.ManyToManyField("resume.ToolsUsed", verbose_name=("Tools Used"))

    class Meta:
        verbose_name = "ResumeProject"
        verbose_name_plural = "ResumeProjects"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ResumeProject_detail", kwargs={"pk": self.pk})


class ResumeProjectDetail(models.Model):

    associated_project = models.ForeignKey(ResumeProject, on_delete=models.CASCADE)
    detail_short = models.CharField(("Short Detail"), max_length=100)
    explanation = models.CharField(("Longer Explanation"), max_length=250)

    class Meta:
        verbose_name = "ResumeProjectDetail"
        verbose_name_plural = "ResumeProjectDetails"

    def __str__(self):
        return "{} - {}".format(self.associated_project.name, self.detail_short)

    def get_absolute_url(self):
        return reverse("ResumeProjectDetail_detail", kwargs={"pk": self.pk})


class ToolsUsed(models.Model):
    tool_name = models.CharField(("Tool Name"), max_length=50)
    tool_color = models.CharField(("Tool Color"), max_length=50)

    def __str__(self):
        return self.tool_name


class RelatedLinks(models.Model):
    related_project = models.ForeignKey(
        "resume.ResumeProject", on_delete=models.CASCADE
    )
    link_name = models.CharField(("Link Name"), max_length=50)
    link_url = models.CharField(("Link"), max_length=250)

    def __str__(self):
        return "{} - {}".format(self.related_project.name, self.link_name)

    class Meta:
        verbose_name = "RelatedLinks"
        verbose_name_plural = "RelatedLinks"

resume/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import ResumeProject, ResumeProjectDetail

# Create your views here.
def home(request):
    return render(request, "home.html")


def contact(request):
    return render(request, "contact.html")


def about(request):
    return render(request, "about.html")


def hobbies(request):
    return render(request, "hobbies.html")


class ProjectListView(ListView):
    model = ResumeProject
    context_object_name = "projects"
    template_name = "projects_list.html"

    def get_queryset(self):
        return ResumeProject.objects.all().order_by("-difficulty", "start_date")


class ProjectDetailView(DetailView):
    model = ResumeProject
    context_object_name = "project"
    template_name = "project_detail.html"

    def get_queryset(self):
        return (
            ResumeProject.objects.filter(pk=self.kwargs["pk"])
            .select_related()
            .prefetch_related()
        )

templates/about.html
{% extends 'main.html' %} {% block main_content %} {% load static %}
<div class="container-fluid bg-light extended_bottom">
  <div class="row justify-content-center title_block">
    <div class="col text-center">
      <p id="page_title">About Me</p>
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-6">
      <img
        id="resize_img"
        src="{% static 'portfolio/pics/computer_image_aboutme.jpg' %}"
        alt="picture of a computer with python"
        class="img-thumbnail img-responsive"
      />
    </div>
    <div class="col-sm-4 text-center">
      <h3>Hi I'm Hiren, a Software Engineer from Lathrop, California.</h3>
      {% comment %}
      <p class="text-center">
        Hi, I'm Hiren a Software Engineer from Lathrop, California.
      </p>
      {% endcomment %}
    </div>
  </div>
  <div class="row justify-content-center top_buffer">
    <div class="col-sm-10">
      <p class="text-sm-left lead">
        Over the past few years, I've gone from being a hobby dev to becoming a
        full-fledged software engineer. Some of the projects that I've completed
        in my past range from school assignments, personal projects, hackathon,
        or work-related projects.
      </p>
      <p class="text-sm-left lead">
        Most of my work is largely written in Java, Python, and Rust(recently).
        I have made web-applications, mobile applications, stand-alone desktop
        applications, CLI applications, custom ETL jobs, and log parsers.
        Currently, I am pursuing a master's degree now at the Georgia Institute
        of Technology with a specialization in Computing Systems.
      </p>
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-5 text-center">
      <p class="text-sm-left lead font-weight-bold">
        From a hobby dev to software engineer...
      </p>
      <p class="text-sm-left">
        My introduction to programming came when I was pursuing a degree in
        Clinical Nutrition at San Jose State University. I had registered for a
        C Programming class to meet my unit requirements for the semester. It
        was not an easy transition to make as a bio major trying to understand
        the fundamentals of computing. Oddly enough, I thrived on the challenge
        and ended passing with an A+. This was the motivation for me to take
        another class in Java programming at SJSU which I subsequently passed
        with an A as well. The meanwhile I continued along the path to complete
        my degree in Clinical Nutrition.
      </p>
    </div>
    <div class="col-sm-5">
      <img
        id="resize_img"
        src="{% static 'portfolio/pics/microscop_image_stock.jpg' %}"
        alt="picture of a microscope"
        class="img-thumbnail img-responsive"
      />
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-5 text-center">
      <img
        id="resize_img"
        src="{% static 'portfolio/pics/surgery_room.jpg' %}"
        alt="picture of a surgery room"
        class="img-thumbnail img-responsive"
      />
    </div>
    <div class="col-sm-5 text-center">
      <p class="text-sm-left">
        While going to school, I also worked as an Inpatient Pharmacy Technician
        to fund college. Over the years, I noticed several problems that usually
        caused delays down the chain. Some of these problems include finding
        optimal medication levels in our automated dispensing machines. Others
        included logistics of tracking narcotics through the life cycle of a
        surgery case by reconciling documentation from multiple systems. Some of
        my initial Python code was an effort to solve the aforementioned
        problems through the PANDAS and Requests libraries. I was able to reduce
        the time spent reconciling narcotics in surgery cases by creating a
        script to combine data from the health-records and the dispensing
        machines. This was able to cut down a 2-week full-time job to a 2-day
        full-time job saving hours and increasing accuracy.
      </p>
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-5 text-center">
      <p class="text-sm-left">
        This was the precursor to a hobby which would eventually lead me to
        change my degree path. There was also a shift in thinking, whereas
        people saw issues, I saw optimizations waiting to happen. This was also
        when I accepted a job offer to work as a Lead IT Support Analyst, which
        was drastically different from working in a hospital setting. Towards my
        last year at SJSU, I had decided to pursue a Bachelor of Software
        Development at Western Governors University. The change was sudden, but
        I had felt that it would serve to challenge me intellectually. At this
        point, I had also gone through a Grow With Google scholarship which
        introduced me to Android Development and had me making Android
        applications.
      </p>
    </div>
    <div class="col-sm-5 text-center">
      <img
        id="resize_img"
        src="{% static 'portfolio/pics/computer_image_html.jpg' %}"
        alt="picture of a surgery room"
        class="img-thumbnail img-responsive"
      />
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-10 text-center">
      <p class="text-sm-left">
        While going to school and working full time, I was able to develop many
        more pieces of code that helped solve problems in an enterprise setting.
        I even got a chance to compete in a hackathon trying to develop Voice-UI
        for Alexa based applications that fit multiple user stories.
      </p>
    </div>
  </div>
  <div class="row justify-content-center align-items-center large-top-buffer">
    <div class="col-sm-10 text-center large_top_buffer">
      <p class="text-sm-left lead">
        I finished my Software Development degree in April 2020 and am currently
        pursuing a Master's Degree in Computer Science with a specialization in
        Computing Systems at Georgia Institute of Technology.
      </p>
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-3 mt-2">
      <a
        href="https://drive.google.com/file/d/1KgAH1-GFvo6RTr7HeLQYesIFKzRdIJGB/view"
        class="btn btn-primary btn-block"
        role="button"
        >Resume</a
      >
    </div>
    <div class="col-sm-3 mt-2">
      <a
        href="{% url 'projects' %}"
        class="btn btn-primary btn-block"
        role="button"
        >Portfolio</a
      >
    </div>
    <div class="col-sm-3 mt-2">
      <a
        href="{% url 'contact_link' %}"
        class="btn btn-primary btn-block"
        role="button"
        >Contact</a
      >
    </div>
  </div>
</div>

{% endblock main_content %}

templates/contact.html
{% extends 'main.html' %} {% block main_content %} {% load static %}
<div class="container-fluid bg-light extended_bottom">
  <div class="row justify-content-center title_block">
    <div class="col text-center">
      <p id="page_title">Contact Me</p>
    </div>
  </div>
  <div class="row justify-content-center align-items-center top_buffer">
    <div class="col-sm-5 text-center top_buffer">
      <a
        class="link-card"
        href="mailto:hirenpatelca@gmail.com"
        data-toggle="tooltip"
        title="Send email to me"
      >
        <i
          id="fa-icon-large"
          class="fa fa-envelope-o fa-5x"
          aria-hidden="true"
        ></i>
      </a>
    </div>

    <div class="col-sm-5 text-center top_buffer">
      <a
        class="link-card"
        href="#"
        data-toggle="tooltip"
        title="Follow me on LinkedIn"
      >
        <i
          id="fa-icon-large"
          class="fa fa-linkedin fa-5x"
          aria-hidden="true"
        ></i>
      </a>
    </div>
  </div>
</div>

{% endblock main_content %}

templates/hobbies.html
{% extends 'main.html' %} {% load static %} {% block main_content %}

<div class="container-fluid bg-light">
  <div class="row justify-content-center project-title-block">
    <p class="display-4">Coming Soon!</p>
  </div>
</div>

{% endblock main_content %}

templates/home.html
{% extends 'main.html' %} {% block main_content %} {% load static %}
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">Hi, I'm Hiren!</h1>
      <p class="lead text-muted">
        A software engineer, on the ever long quest for more knowledge.
      </p>
      <p></p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <a class="link-card" href="{% url 'about_me' %}">
            <div class="card mb-4 box-shadow">
              <img
                class="card-img-top"
                src="{% static 'portfolio/pics/car_universe_bg.jpg' %}"
                alt="About Me"
              />
              <div class="card-body">
                <h5 class="card-title">About Me</h5>
                <p class="card-text">
                  A little bit about me, my background in CS, as well as outside
                  of it.
                </p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-md-4">
          <a class="link-card" href="{% url 'projects' %}">
            <div class="card mb-4 box-shadow">
              <img
                class="card-img-top"
                src="{% static 'portfolio/pics/computer_python_image.jpg' %}"
                alt="My Projects"
              />
              <div class="card-body">
                <h5 class="card-title">Projects</h5>
                <p class="card-text">
                  Some of my past and current CS projects, source code
                  linked(where possible).
                </p>
              </div>
            </div>
          </a>
        </div>
        <div class="col-md-4">
          <a class="link-card" href="{% url 'my_hobbies' %}">
            <div class="card mb-4 box-shadow">
              <img
                class="card-img-top"
                src="{% static 'portfolio/pics/cooking_image_stock_1.jpg' %}"
                alt="My Hobbies"
              />
              <div class="card-body">
                <h5 class="card-title">Hobbies</h5>
                <p class="card-text">
                  Hobbies outside of CS, such as cooking, teaching my dog to
                  stay, etc.
                </p>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock main_content %}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Hiren Patel Portfolio</title>

    <!-- Bootstrap core CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- Custom styles for this template -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'portfolio/main.css' %}"
    />
  </head>

  <body>
    <header>
      <nav class="shadow navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'home' %}">Hiren Patel</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse alight-items-center"
          id="navbarSupportedContent"
        >
          <ul class="navbar-nav ml-auto align-items-center">
            <li class="nav-item">
              <a
                class="nav-link"
                href="https://www.linkedin.com/in/hiren-patel-319629153/"
                ><i
                  id="fa-icon"
                  class="fa fa-linkedin-square fa-6"
                  aria-hidden="true"
                ></i
              ></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://github.com/hpca01/"
                ><i
                  id="fa-icon"
                  class="fa fa-github-square fa-6"
                  aria-hidden="true"
                ></i
              ></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about_me' %}">About Me</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'projects' %}">Portfolio</a>
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                href="https://drive.google.com/file/d/1KgAH1-GFvo6RTr7HeLQYesIFKzRdIJGB/view"
                >Resume</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'contact_link' %}">Contact</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>

    {% block main_content %} {% endblock main_content %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/project_detail.html
{% extends 'main.html' %} {% block main_content %} {% load static %}
<div class="container-fluid bg-light extended_bottom">
  <div class="row justify-content-center project-title-block">
    <div class="col text-center">
      <p>{{project.name}}</p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <p class="lead">{{project.quick_blurb}}</p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-6 text-center">
      <img src="{{project.main_img.url}}" class="img-fluid" />
    </div>
  </div>
  <div class="row justify-content-center mt-5">
    <div class="col-sm-8 text-center">
      <p class="text-sm-left">{{project.long_description}}</p>
    </div>
  </div>
  {% for detail in project.resumeprojectdetail_set.all %}
  <div class="row justify-content-center mt-2">
    <div class="col-sm-2 text-center">
      <p class="font-weight-bold">{{detail.detail_short}}</p>
    </div>
    <div class="col-sm-6 text-left">{{detail.explanation}}</div>
  </div>
  {% endfor %}
  <div class="row justify-content-center mt-5">
    <div class="col-sm-4 text-center">
      <p class="lead">Tools Used:</p>
      {% for tool in project.tools_used.all %}
      <span
        class="badge badge-primary badge-font-big mt-2"
        style="background-color:{{tool.tool_color}} !important;"
        >{{tool.tool_name}}</span
      >
      {% endfor %}
    </div>
    <div class="col-sm-4 text-center">
      {% if project.git_link %}
      <p class="lead">Links:</p>
      <a href="{{project.git_link}}" class="btn btn-secondary mt-2">Github</a>
      {% endif %} {% for link in project.relatedlinks_set.all %}
      <a class="btn btn-primary mt-2" href="{{link.link_url}}" role="button"
        >{{link.link_name}}</a
      >
      {% endfor %}
    </div>
  </div>
</div>

{% endblock main_content %}

templates/projects_list.html
{% extends 'main.html' %} {% block main_content %}
<div class="container-fluid bg-light extended_bottom">
  <div class="row justify-content-center title_block">
    <div class="col text-center">
      <p id="page_title">Projects</p>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-sm-5">
      {% for project in projects %} {% if forloop.counter0|divisibleby:2 %}
      <a class="link-card" href="{% url 'project' project.id %}">
        <div class="card box-shadow mt-3">
          <div class="row justify-content-center align-items-center">
            <div class="col-sm-7 d-none d-lg-block">
              <!--add an if statement which moves this and the other column back and forth based on index-->
              <img
                class="card-img card-img-horizontal-size"
                src="{{ project.main_img.url }}"
                alt=""
              />
            </div>
            <div class="col-sm-5">
              <div class="card-body">
                <h5 class="card-title text-right">{{project.name}}</h5>
                <p class="card-text text-right">{{project.quick_blurb}}</p>
              </div>
            </div>
          </div>
        </div>
      </a>
      {% else %}
      <a class="link-card" href="{% url 'project' project.id %}">
        <div class="card box-shadow mt-3">
          <div class="row no-gutters justify-content-center align-items-center">
            <div class="col-sm-5">
              <div class="card-body">
                <h5 class="card-title text-right">{{project.name}}</h5>
                <p class="card-text text-right">{{project.quick_blurb}}</p>
              </div>
            </div>
            <div class="col-sm-7 d-none d-lg-block">
              <!--add an if statement which moves this and the other column back and forth based on index-->
              <img
                class="card-img card-img-horizontal-size"
                src="{{ project.main_img.url }}"
                alt="project image"
              />
            </div>
          </div>
        </div>
      </a>
      {% endif %} {% endfor %}
    </div>
  </div>
</div>

{% endblock main_content %}